### ISSUE TITLE
Show outdated packages links

### ISSUE THREAD

**Issue by Soullivaneuh** [Soullivaneuh/composer-versions-check#13]
Some outdated packages are sub-dependencies of composer project.

In this cases, show them on the result.

Go up to the root dependencies (packages defined directly on `composer.json` file).

Note: To help, take a look to `composer depends` command.

**Comment by Soullivaneuh** [comment]
Not sure if very useful because we got enough information with the `depends` command:

```bash
Some packages are not up to date:

 - a2lix/translation-form-bundle (1.3) last version is 2.0.4
 - phenx/php-font-lib (0.2.2) last version is 0.4
 - fabpot/goutte (v1.0.7) last version is v3.1.1
 - guzzlehttp/guzzle (5.3.0) last version is 6.1.0
 - lexik/paybox-bundle (v1.1.0) last version is v2.0.1
 - sensio/distribution-bundle (v3.0.31) last version is v4.0.1
 - michelf/php-markdown (1.4.1) last version is 1.5.0
 - willdurand/negotiation (1.5.0) last version is v2.0.1
$ composer depends willdurand/negotiation
friendsofsymfony/rest-bundle requires willdurand/negotiation (~1.2)
$ composer depends phenx/php-font-lib
dompdf/dompdf requires phenx/php-font-lib (0.2.*)
```

Maybe show this output directly with this plugin, or as an option (if possible).

Waiting users feedback for this. :+1: or :-1:?

**Comment by Soullivaneuh** [comment]
Maybe propose it as an option.

Have to check if extra options works with composer plugins.

In this case, try to use `depends` command process and option resolver.

**Comment by EmanueleMinotto** [comment]
I'm against this :-1: for two reasons:

1. introduces a lot of complexity transforming the graph of dependencies in a single `Traversable|array`
2. if the final developer adds a "2nd level dependency" to the root composer.json before the "1st level dependency" than he/she will probably solve the dependency for the moment *t1* but if, in a moment *t2* updates the "1st level dependency", this will have another version of that "2nd level dependency" or other dependencies, than he/she needs to check every other new "1st level dependency" introduced in *t1* if them are still required or not (without considering business code changes)

**Comment by Soullivaneuh** [comment]
@EmanueleMinotto Thanks for your participation! :+1: 

1. I globally agree, that's could be more complex and consume more resources. But that's why I would like to propose it as an option, disabled by default.
2. I'm sorry but I'm not sure to understand. What do you mean by "adds a "2nd level dependency" to the root composer.json before the "1st level dependency""? Do you have a concrete sample?

**Comment by EmanueleMinotto** [comment]
Nothing concrete but I can write an example:

**t1**: *project/root*
```json
{
  "require": {
    "vendor/foo": "~1.0"
  }
}
```

**t1**: *vendor/foo*
```json
{
  "require": {
    "vendor/bar": "~1.0"
  }
}
```

Consider `vendor/bar` already outdated (the v1.2 of `vendor/bar` already exists), so the final developer changes the composer.json to:

**t2**: *project/root*
```json
{
  "require": {
    "vendor/foo": "~1.0",
    "vendor/bar": "~1.2"
  }
}
```

In a **t3**, *vendor/foo* removes *vendor/bar* from its dependencies, and in that moment *project/root* has a pending/unused dependency.

This is the most optimistic case, because if in a **t4** another dependency conflicts with *vendor/bar* than the final developer has to check every dependency if it's really used or not.

**Comment by Soullivaneuh** [comment]
I think I understand you sample. Some points:

* Your sample is not correct. Would be correct if the deps constraint was `1.0.*` for example. But I understood the goal. ;-)
* The goal of showing dependencies is not to add new versions on the root package. BTW, with a strictly locked vendor deps, that would produce conflicts. No, it's just to warn user that some vendor does not have an up to date composer config file. Starting this point, the user could make a PR on the concerned vendor if he want it.

> this is a really interesting project.

Thanks! :-)

**Comment by EmanueleMinotto** [comment]
With the right warning, or even better a "danger", message than I agree too :+1:

**Comment by Soullivaneuh** [comment]
I don't see which message I can put.

As I said, if the outdated package is not a root dependencies, it necessary because another dependencies has an outdated constraint.

So, in any case, if the developer want to add the package with an up to date constraint on his root project, this will not work.

I'll ping you when the PR will be pushed.
