### ISSUE TITLE
thephpleague proposal

### ISSUE THREAD

**Issue by EmanueleMinotto** [Soullivaneuh/composer-versions-check#17]
Considering the utility for all the PHP community, I think this should be proposed to http://thephpleague.com (not to composer because this isn't its responsability, imo).

This mean that [skeleton](https://github.com/thephpleague/skeleton) conventions should be applied before submitting a message into their mailing list.

What about it? I can send a PR if it's interesting.

**Comment by Soullivaneuh** [comment]
If I understand well the goal of thephpleague, I'll have to move this project under them namespace, isn't it?

In this case, I'm not really interesting of moving this for the moment.

For just reference, why not.

**Comment by EmanueleMinotto** [comment]
Yes, also that is a requirement :\ no problem, closing.
