### ISSUE TITLE
Redeclared class error on require

### ISSUE THREAD

**Issue by SteveEdson** [Soullivaneuh/composer-versions-check#23]
When creating a new directory and running

`composer require twig/twig`

I get the error:

```
$ composer require twig/twig
Using version ^1.23 for twig/twig
./composer.json has been updated
PHP Fatal error:  Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 19

Fatal error: Cannot redeclare class SLLH\ComposerVersionsCheck\VersionsCheckPlugin in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(246) : eval()'d code on line 19
```

Running `$ composer update` afterwards works fine.

Thanks.

**Comment by EmanueleMinotto** [comment]
Should be related to https://github.com/Soullivaneuh/composer-versions-check/issues/9

**Comment by Soullivaneuh** [comment]
Did you install the plugin globally or locally?

**Comment by SteveEdson** [comment]
Installed globally. Thanks

**Comment by Soullivaneuh** [comment]
@SteveEdson Please see https://github.com/composer/composer/pull/4482.

Seems to be a composer issue.

**Comment by SteveEdson** [comment]
Thanks, I'll keep track of that issue. It's not a deal breaker at the moment.

**Comment by Soullivaneuh** [comment]
Fixed in https://github.com/composer/composer/commit/977b8c8f41be12d342c32d27a7b8421ed8e6a3de.

Please upgrade your composer binary.
