### ISSUE TITLE
branch-alias is not handled

### ISSUE THREAD

**Issue by garak** [Soullivaneuh/composer-versions-check#46]
Quick example: I'm using `"friendsofsymfony/user-bundle": "~2.0@dev"` as dependency.
The final message is containing:

```
- friendsofsymfony/user-bundle (2.0.x-dev) latest is dev-master
```

that is wrong, since `dev-master` and `2.0.x-dev` are actually the same version (defined via `branch-alias` in FOSUserBundle)

**Comment by sstok** [comment]
I think this can be easily fixed.

If you detect the package is outdated. Get the version of the branch-alias and see if the latest is by constraint equal, if equal remove it as being outdated. (not tested).

**Comment by garak** [comment]
Any news on this?

**Comment by Soullivaneuh** [comment]
@garak Should be working with [v2.0.3](https://github.com/Soullivaneuh/composer-versions-check/releases/tag/v2.0.3).

Sorry for the delay.
