### ISSUE TITLE
Problem with composer update now

### ISSUE THREAD

**Issue by dereuromark** [soullivaneuh/composer-versions-check#48]
Updating ...
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                       
  Call to undefined method Composer\DependencyResolver\Operation\UpdateOperation::getPackage() 
```
It looks like it is caused by VersionsCheckPlugin::postUpdate() call to getPackage()?

//edit: OK, maybe it is not this kind of call after all.. Not sure why it fails today now.

**Comment by dereuromark** [comment]
PS: The README should also explain how to remove this plugin again if needed.

**Comment by Soullivaneuh** [comment]
Hello @dereuromark,

Could you please give me more information?

* Result of `composer --version`.
* Result of your update command with verbosity (`-vvv`).
* Content of your `composer.json` file.

This will help investigate the issue.

> PS: The README should also explain how to remove this plugin again if needed.

What do you mean by that? It's a simple composer package that can be removed with `composer remove` command.
